# Generated by Django 5.1.1 on 2024-10-21 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0004_remove_orden_cantidad_remove_orden_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenproducto',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='ordenproducto',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Orden',
        ),
        migrations.DeleteModel(
            name='OrdenProducto',
        ),
    ]
